# Generated by Django 5.2.4 on 2025-07-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_job_estimated_arrival_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('sub_heading', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('experience_years', models.CharField(default='25+ Years Experience', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
